name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-incident-io
        run: go build ./cmd/baton-incident-io
      - name: Run baton-incident-io
        run: ./baton-incident-io --token="${{ secrets.API_TOKEN }}"

      - name: Run capabilities
        run: ./baton-incident-io capabilities
